title: Jago Strong-Wright
description: > # this means to ignore newlines until "baseurl:"
  Some of my projects and work
permalink: ':title/'
baseurl: "/jago" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: jagosw #if your site has a twitter account, enter it here

# Author Settings
author: Jago Strong-Wright # add your name
author-img: profile.jpg # add your photo
about-author: I'm a physics student at the University of Cambridge. I'm interested in spaceflight, programming, additive manufacturing among many others things. # add description
social-twitter: jagosw # add your Twitter handle
social-facebook: jago.strongwright # add your Facebook handle
social-github: jagoosw # add your Github handle
social-linkedin: jagosw # add your Linkedin handle
social-email: js2430@cam.ac.uk # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
